-- $Id$
--[[

	Atlas, a World of Warcraft instance map browser
	Copyright 2005 ~ 2010 - Dan Gilbert <dan.b.gilbert@gmail.com>
	Copyright 2010 - Lothaer <lothayer@gmail.com>, Atlas Team
	Copyright 2011 ~ 2026 - Arith Hsu, Atlas Team

	This file is part of Atlas.

	Atlas is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 2 of the License, or
	(at your option) any later version.

	Atlas is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with Atlas; if not, write to the Free Software
	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

--]]
local _G = getfenv(0)
-- Area IDs for the Progression Classic version of World of Warcraft. Source is from AreaID table.
local projectID = WOW_PROJECT_ID
local PROJECT_CATA = WOW_PROJECT_CATACLYSM_CLASSIC
local PROJECT_MISTS = WOW_PROJECT_MISTS_CLASSIC
local isCataclysmClassic = PROJECT_CATA ~= nil and projectID == PROJECT_CATA
local isMistsClassic = PROJECT_MISTS ~= nil and projectID == PROJECT_MISTS
local isProgressionClassic = isCataclysmClassic or isMistsClassic
if not isProgressionClassic then return end

-- ----------------------------------------------------------------------------
-- AddOn namespace.
-- ----------------------------------------------------------------------------
local FOLDER_NAME, private = ...

local LibStub = _G.LibStub

local BZ = Atlas_GetLocaleLibBabble("LibBabble-SubZone-3.0")
local BF = Atlas_GetLocaleLibBabble("LibBabble-Faction-3.0")
local L = LibStub("AceLocale-3.0"):GetLocale(private.addon_name)
local ALC = LibStub("AceLocale-3.0"):GetLocale("Atlas")
local Atlas = LibStub("AceAddon-3.0"):GetAddon("Atlas")

local data = {}
local alliance = {}
local horde = {}
private.data = data
private.alliance = alliance
private.horde = horde

local BLUE = "|cff6666ff"
local GREN = "|cff66cc33"
local _RED = "|cffcc3333"
local ORNG = "|cffcc9933"
local PURP = "|cff9900ff"
local WHIT = "|cffffffff"
local LBLU = "|cff33cccc"
local CYAN = "|cff00ffff"
local GREY = "|cff999999"
local ALAN = "|cff7babe0" -- Alliance's taxi node
local HRDE = "|cffda6955" -- Horde's taxi node
local NUTL = "|cfffee570" -- Nutral taxi node
local INDENT = "      "

local CL = {
	["HUNTER"] 	= "|cffabd473",
	["WARLOCK"] 	= "|cff8788ee",
	["PRIEST"] 	= "|cffffffff",
	["PALADIN"] 	= "|cfff58cba",
	["MAGE"] 	= "|cff3fc7eb",
	["ROGUE"] 	= "|cfffff569",
	["DRUID"] 	= "|cffff7d0a",
	["SHAMAN"] 	= "|cff0070de",
	["WARRIOR"] 	= "|cffc79c6e",
	["DEATHKNIGHT"]	= "|cffc41f3b",
	["MONK"] 	= "|cff00ff96",
	["DEMONHUNTER"]	= "|cffa330c9",
}


alliance.maps = {
	TransAllianceCosmos_WOLTKC = {
		ZoneName = { WORLD..ALAN..ALC["L-Parenthesis"]..FACTION_ALLIANCE..ALC["R-Parenthesis"] },
		{ BLUE..BZ["Kalimdor"] },
		{ WHIT.." 1) "..BZ["Darnassus"]..ALC["Comma"].._RED..BZ["Teldrassil"], 10001 },
		{ WHIT.." 2) "..BZ["Rut'theran Village"]..ALC["Comma"].._RED..BZ["Teldrassil"], 10002 },
		{ WHIT.." 3) "..BZ["Auberdine"]..ALC["Comma"].._RED..BZ["Darkshore"], 10003 },
		{ WHIT.." 4) "..BZ["The Exodar"]..ALC["Comma"].._RED..BZ["Azuremyst Isle"], 10004 },
		{ WHIT.." 5) "..BZ["Nighthaven"]..ALC["Comma"].._RED..BZ["Moonglade"], 10005 },
		{ NUTL.." 6) "..BZ["Ratchet"]..ALC["Comma"].._RED..BZ["The Barrens"], 10006 },
		{ WHIT.." 7) "..BZ["Theramore"]..ALC["Comma"].._RED..BZ["Dustwallow Marsh"], 10007 },
		{ PURP.." B) "..BZ["The Shaper's Terrace"]..ALC["Comma"]..BZ["Un'Goro Crater"] },
		{ PURP.." C) "..BZ["Caverns of Time"]..ALC["Comma"]..BZ["Tanaris"] },
		{ "" },
		{ BLUE..BZ["Eastern Kingdoms"] },
		{ WHIT.." 8) "..BZ["Menethil Harbor"]..ALC["Comma"].._RED..BZ["Wetlands"], 10008 },
		{ WHIT.." 9) "..BZ["Ironforge"]..ALC["Comma"].._RED..BZ["Dun Morogh"], 10009 },
		{ WHIT.."10) "..BZ["Stormwind"]..ALC["Comma"].._RED..BZ["Elwynn Forest"], 10010 },
		{ NUTL.."11) "..BZ["Booty Bay"]..ALC["Comma"].._RED..BZ["Stranglethorn Vale"], 10011 },
		{ WHIT.."12) "..BZ["Shattered Beachhead"]..ALC["Comma"].._RED..BZ["Blasted Lands"], 10012 },
		{ WHIT.."13) "..BZ["Shattered Sun Staging Area"]..ALC["Comma"].._RED..BZ["Isle of Quel'Danas"], 10013 },
		{ "" },
		{ BLUE..BZ["Outland"] },
		{ WHIT.."14) "..BZ["The Stair of Destiny"]..ALC["Comma"].._RED..BZ["Hellfire Peninsula"], 10014 },
		{ NUTL.."15) "..BZ["Shattrath City"]..ALC["Comma"].._RED..BZ["Terokkar Forest"], 10015 },
		{ "" },
		{ BLUE..BZ["Northrend"] },
		{ WHIT.."16) "..BZ["Valiance Keep"]..ALC["Comma"].._RED..BZ["Borean Tundra"] };
		{ NUTL.."17) "..BZ["Dalaran"]..ALC["Comma"].._RED..BZ["Crystalsong Forest"] };
		{ WHIT.."18) "..BZ["Valgarde"]..ALC["Comma"].._RED..BZ["Howling Fjord"] };
		{ PURP.." A) "..BZ["Waygate"]..ALC["Comma"]..BZ["Sholazar Basin"] },
	},
	TransAllianceEast_ClassicProgression = {
		ZoneName = { BZ["Eastern Kingdoms"]..ALAN..ALC["L-Parenthesis"]..FACTION_ALLIANCE..ALC["R-Parenthesis"] };
		WorldMapID = 13,
		Faction = "Alliance",
		{ _RED..BZ["Docks"] };
		{ ORNG.." A') "..BZ["Valgarde"]..ALC["Comma"]..BZ["Howling Fjord"]..ALC["Comma"]..BZ["Northrend"] };
		{ ORNG.." B') "..BZ["Valiance Keep"]..ALC["Comma"]..BZ["Borean Tundra"]..ALC["Comma"]..BZ["Northrend"] };
		{ ORNG.." C') "..BZ["Rut'theran Village"]..ALC["Comma"]..BZ["Teldrassil"]..ALC["Comma"]..BZ["Kalimdor"] };
		{ ORNG.." D') "..BZ["Ratchet"]..ALC["Comma"]..BZ["Northern Barrens"]..ALC["Comma"]..BZ["Kalimdor"] };
		{ ORNG.." E') "..BZ["Theramore"]..ALC["Comma"]..BZ["Dustwallow Marsh"]..ALC["Comma"]..BZ["Kalimdor"] };
		{ WHIT.."21) "..BZ["Menethil Harbor"]..ALC["Comma"]..BZ["Wetlands"] };
		{ WHIT.."43) "..BZ["Stormwind Harbor"]..ALC["Comma"]..BZ["Elwynn Forest"] };
		{ WHIT.."60) "..BZ["Booty Bay"]..ALC["Comma"]..BZ["The Cape of Stranglethorn"] };
		{ "" };
		{ _RED..L["Portals"]..ALC["Slash"]..L["Transporter"] };
		{ PURP.." A) "..BZ["Baradin Base Camp"]..ALC["Comma"]..BZ["Tol Barad Peninsula"] };
		{ PURP.." B) "..BZ["Baradin Hold"]..ALC["Comma"]..BZ["Tol Barad"] };
		{ PURP..INDENT.."("..L["Only available after winning the PvP battle"]..ALC["R-Parenthesis"] };
		{ PURP.." C) "..BZ["Highbank"]..ALC["Comma"]..BZ["Twilight Highlands"] };
		{ PURP.." D) "..BZ["Fuselight-by-the-Sea"]..ALC["Comma"]..BZ["Badlands"] };
		{ PURP..INDENT.."("..L["Transporters by the sea and on the cliff"]..ALC["R-Parenthesis"] };
		{ PURP.." E) "..BZ["The Dark Portal"]..ALC["Comma"]..BZ["Blasted Lands"] };
		{ PURP.." A') "..BZ["Nordrassil"]..ALC["Comma"]..BZ["Mount Hyjal"]..ALC["Comma"]..BZ["Kalimdor"] };
		{ PURP.." B') "..BZ["Ramkahen"]..ALC["Comma"]..BZ["Uldum"]..ALC["Comma"]..BZ["Kalimdor"] };
		{ PURP.." C') "..BZ["The Stair of Destiny"]..ALC["Comma"]..BZ["Hellfire Peninsula"]..ALC["Comma"]..BZ["Outland"] };
		{ PURP.." D') "..BZ["Temple of Earth"]..ALC["Comma"]..BZ["Deepholm"] };
		{ PURP.." E') "..BZ["Darkmoon Island"] };
		{ PURP.." F') "..BZ["Paw'Don Village"]..ALC["Comma"]..BZ["The Jade Forest"]..ALC["Comma"]..BZ["Pandaria"] };
		{ WHIT.."29) "..BZ["The Mystic Ward"]..ALC["Comma"]..BZ["Ironforge"]..ALC["Comma"]..BZ["Dun Morogh"] };
		{ WHIT.."43) "..BZ["Mage Quarter"]..ALC["Comma"]..BZ["Stormwind"]..ALC["Comma"]..BZ["Elwynn Forest"] };
		{ "" };
		{ _RED..L["Taxi Nodes"] };
		{ BLUE..BZ["Isle of Quel'Danas"] };
		{ WHIT.." 1) "..BZ["Shattered Sun Staging Area"] };
		{ "" };
		{ BLUE..BZ["Ghostlands"] };
		{ WHIT.." 2) "..BZ["Zul'Aman"] };
		{ "" };
		{ BLUE..BZ["Eastern Plaguelands"] };
		{ GREN.." 3) "..BZ["Acherus: The Ebon Hold"]..ALC["L-Parenthesis"]..L["Death Knight Only"]..ALC["R-Parenthesis"] };
		{ WHIT.." 4) "..BZ["Light's Hope Chapel"] };
		{ WHIT.." 5) "..BZ["Eastwall Tower"] };
		{ WHIT.." 6) "..BZ["Northpass Tower"] };
		{ WHIT.." 7) "..BZ["Plaguewood Tower"] };
		{ WHIT.." 8) "..BZ["Light's Shield Tower"] };
		{ WHIT.." 9) "..BZ["Crown Guard Tower"] };
		{ WHIT.."10) "..BZ["Thondroril River"] };
		{ "" };
		{ BLUE..BZ["Western Plaguelands"] };
		{ WHIT.."11) "..BZ["Hearthglen"] };
		{ WHIT.."12) "..BZ["The Menders' Stead"] };
		{ WHIT.."13) "..BZ["Andorhal"] };
		{ WHIT..INDENT..ALC["L-Parenthesis"]..L["Won't be available once the Battle for Andorhal chain is finished."]..ALC["R-Parenthesis"] };
		{ WHIT.."14) "..BZ["Chillwind Camp"] };
		{ "" };
		{ BLUE..BZ["The Hinterlands"] };
		{ WHIT.."15) "..BZ["Aerie Peak"] };
		{ WHIT.."16) "..BZ["Stormfeather Outpost"] };
		{ "" };
		{ BLUE..BZ["Arathi Highlands"] };
		{ WHIT.."17) "..BZ["Refuge Pointe"] };
		{ "" };
		{ BLUE..BZ["Wetlands"] };
		{ WHIT.."18) "..BZ["Dun Modr"] };
		{ WHIT.."19) "..BZ["Whelgar's Retreat"] };
		{ WHIT.."20) "..BZ["Greenwarden's Grove"] };
		{ WHIT.."21) "..BZ["Menethil Harbor"] };
		{ WHIT.."22) "..BZ["Slabchisel's Survey"] };
		{ "" };
		{ BLUE..BZ["Twilight Highlands"] };
		{ WHIT.."23) "..BZ["Vermillion Redoubt"] };
		{ WHIT.."24) "..BZ["Thundermar"] };
		{ WHIT.."25) "..BZ["Kirthaven"] };
		{ WHIT.."26) "..BZ["Victor's Point"] };
		{ WHIT.."27) "..BZ["Firebeard's Patrol"] };
		{ WHIT.."28) "..BZ["Highbank"] };
		{ "" };
		{ BLUE..BZ["Dun Morogh"] };
		{ WHIT.."29) "..BZ["Ironforge"] };
		{ WHIT.."30) "..BZ["Kharanos"] };
		{ WHIT.."31) "..BZ["Gol'Bolar Quarry"] };
		{ "" };
		{ BLUE..BZ["Loch Modan"] };
		{ WHIT.."32) "..BZ["Thelsamar"] };
		{ WHIT.."33) "..BZ["Farstrider Lodge"] };
		{ "" };
		{ BLUE..BZ["Searing Gorge"] };
		{ WHIT.."34) "..BZ["Thorium Point"] };
		{ WHIT.."35) "..BZ["Iron Summit"] };
		{ "" };
		{ BLUE..BZ["Badlands"] };
		{ WHIT.."36) "..BZ["Dragon's Mouth"] };
		{ WHIT.."37) "..BZ["Dustwind Dig"] };
		{ WHIT.."38) "..BZ["Fuselight"] };
		{ "" };
		{ BLUE..BZ["Burning Steppes"] };
		{ WHIT.."39) "..BZ["Chiselgrip"] };
		{ WHIT.."40) "..BZ["Morgan's Vigil"] };
		{ WHIT.."41) "..BZ["Flamestar Post"] };
		{ WHIT.."42) "..BZ["Terror Wing Path"]..ALC["Comma"]..BZ["Burning Steppes"] };
		{ WHIT..INDENT.."("..L["The Bogpaddle Bullet"]..ALC["R-Parenthesis"] };
		{ "" };
		{ BLUE..BZ["Elwynn Forest"] };
		{ WHIT.."43) "..BZ["Stormwind"] };
		{ WHIT.."44) "..BZ["Goldshire"] };
		{ WHIT.."45) "..BZ["Eastvale Logging Camp"] };
		{ "" };
		{ BLUE..BZ["Redridge Mountains"] };
		{ WHIT.."46) "..BZ["Lakeshire"] };
		{ WHIT.."47) "..BZ["Camp Everstill"] };
		{ WHIT.."48) "..BZ["Shalewind Canyon"] };
		{ "" };
		{ BLUE..BZ["Westfall"] };
		{ WHIT.."49) "..BZ["Furlbrow's Pumpkin Farm"] };
		{ WHIT.."50) "..BZ["Moonbrook"] };
		{ WHIT.."51) "..BZ["Sentinel Hill"] };
		{ "" };
		{ BLUE..BZ["Duskwood"] };
		{ WHIT.."52) "..BZ["Raven Hill"] };
		{ WHIT.."53) "..BZ["Darkshire"] };
		{ "" };
		{ BLUE..BZ["Swamp of Sorrows"] };
		{ WHIT.."54) "..BZ["The Harborage"] };
		{ WHIT.."55) "..BZ["Marshtide Watch"] };
		{ WHIT.."56) "..BZ["Bogpaddle"] };
		{ "" };
		{ BLUE..BZ["Northern Stranglethorn"] };
		{ WHIT.."57) "..BZ["Rebel Camp"] };
		{ WHIT.."58) "..BZ["Fort Livingston"] };
		{ "" };
		{ BLUE..BZ["The Cape of Stranglethorn"] };
		{ WHIT.."59) "..BZ["Explorers' League Digsite"] };
		{ WHIT.."60) "..BZ["Booty Bay"] };
		{ "" };
		{ BLUE..BZ["Blasted Lands"] };
		{ WHIT.."61) "..BZ["Nethergarde Keep"] };
		{ WHIT.."62) "..BZ["Surwich"] };
		{ "" };
		{ BLUE..BZ["Vashj'ir"] };
		{ CYAN.."63) "..BZ["Smuggler's Scar"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] };
		{ CYAN.."64) "..BZ["Sandy Beach"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["Slash"]..L["Gryphon"]..ALC["R-Parenthesis"] };
		{ CYAN.."65) "..BZ["Silver Tide Hollow"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] };
		{ CYAN.."66) "..BZ["Tranquil Wash"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] };
		{ CYAN.."67) "..BZ["Voldrin's Hold"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["Slash"]..L["Gryphon"]..ALC["R-Parenthesis"] };
		{ CYAN.."68) "..BZ["Darkbreak Cove"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] };
		{ "" };
		{ _RED..L["Legend"] };
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] };
		{ CYAN.."-- : "..L["Ship / Zeppelin sailing path to destination"] };
		{ GREN.."-- : "..BZ["Deeprun Tram"]..ALC["Slash"]..L["Special transportation"] };
	},
	TransAllianceWest_ClassicProgression = {
		ZoneName = { BZ["Kalimdor"]..ALAN..ALC["L-Parenthesis"]..FACTION_ALLIANCE..ALC["R-Parenthesis"] },
		WorldMapID = 12,
		Faction = "Alliance",
		{ _RED..BZ["Docks"] },
		{ ORNG.." A) "..BZ["Valaar's Berth"]..ALC["Comma"]..BZ["Azuremyst Isle"] },
		{ ORNG.." A') "..BZ["Stormwind Harbor"]..ALC["Comma"]..BZ["Elwynn Forest"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ ORNG.." B') "..BZ["Menethil Harbor"]..ALC["Comma"]..BZ["Wetlands"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ ORNG.." C') "..BZ["Booty Bay"]..ALC["Comma"]..BZ["The Cape of Stranglethorn"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ WHIT.." 3) "..BZ["Rut'theran Village"]..ALC["Comma"]..BZ["Teldrassil"] },
		{ WHIT.."28) "..BZ["Ratchet"]..ALC["Comma"]..BZ["Northern Barrens"] },
		{ WHIT.."32) "..BZ["Theramore"]..ALC["Comma"]..BZ["Dustwallow Marsh"] },
		{ "" },
		{ _RED..L["Portals"]..ALC["Slash"]..BZ["Waygate"] },
		{ PURP.." A) "..BZ["Shaper's Terrace"]..ALC["Comma"]..BZ["Un'Goro Crater"] },
		{ PURP.." B) "..BZ["Nordune Ridge"]..ALC["Comma"]..BZ["Mount Hyjal"] },
		{ PURP.." A') "..BZ["Waygate"]..ALC["Comma"]..BZ["Sholazar Basin"]..ALC["Comma"]..BZ["Northrend"] },
		{ PURP.." B') "..BZ["Molten Front"] },
		{ PURP.." C') "..BZ["Stormwind City"]..ALC["Comma"]..BZ["Elwynn Forest"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." D') "..BZ["The Dark Portal"]..ALC["Comma"]..BZ["Blasted Lands"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ WHIT.." 2) "..BZ["Temple of the Moon"]..ALC["Comma"]..BZ["Darnassus"]..ALC["Comma"]..BZ["Teldrassil"] },
		{ WHIT.." 3) "..BZ["Rut'theran Village"]..ALC["Comma"]..BZ["Teldrassil"] },
		{ WHIT.." 5) "..BZ["The Vault of Lights"]..ALC["Comma"]..BZ["The Exodar"]..ALC["Comma"]..BZ["Azuremyst Isle"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Teldrassil"] },
		{ WHIT.." 1) "..BZ["Dolanaar"] },
		{ WHIT.." 2) "..BZ["Darnassus"] },
		{ WHIT.." 3) "..BZ["Rut'theran Village"] },
		{ "" },
		{ BLUE..BZ["Azuremyst Isle"]..ALC["Slash"]..BZ["Bloodmyst Isle"] },
		{ WHIT.." 4) "..BZ["Azure Watch"] },
		{ WHIT.." 5) "..BZ["The Exodar"] },
		{ WHIT.." 6) "..BZ["Blood Watch"] },
		{ "" },
		{ BLUE..BZ["Darkshore"] },
		{ WHIT.." 7) "..BZ["Lor'danel"] },
		{ WHIT.." 8) "..BZ["Grove of the Ancients"] },
		{ "" },
		{ BLUE..BZ["Ashenvale"] },
		{ WHIT.." 9) "..BZ["Blackfathom Camp"] },
		{ WHIT.."10) "..BZ["Astranaar"] },
		{ WHIT.."11) "..BZ["Forest Song"] },
		{ WHIT.."12) "..BZ["Stardust Spire"] },
		{ "" },
		{ BLUE..BZ["Stonetalon Mountains"] },
		{ WHIT.."13) "..BZ["Windshear Hold"] },
		{ WHIT.."14) "..BZ["Mirkfallon Post"] },
		{ WHIT.."15) "..BZ["Thal'darah Overlook"] },
		{ WHIT.."16) "..BZ["Farwatcher's Glen"] },
		{ WHIT.."17) "..BZ["Northwatch Expedition Base Camp"] },
		{ "" },
		{ BLUE..BZ["Desolace"] },
		{ WHIT.."18) "..BZ["Nijel's Point"] },
		{ WHIT.."19) "..BZ["Thunk's Abode"] },
		{ WHIT.."20) "..BZ["Karnum's Glade"] },
		{ WHIT.."21) "..BZ["Ethel Rethor"] },
		{ WHIT.."22) "..BZ["Thargad's Camp"] },
		{ "" },
		{ BLUE..BZ["Feralas"] },
		{ WHIT.."23) "..BZ["Dreamer's Rest"] },
		{ WHIT.."24) "..BZ["Feathermoon"] },
		{ WHIT.."25) "..BZ["Ruins of Feathermoon"] },
		{ WHIT.."26) "..BZ["Tower of Estulan"] },
		{ WHIT.."27) "..BZ["Shadebough"] },
		{ "" },
		{ BLUE..BZ["Northern Barrens"]..ALC["Slash"]..BZ["Southern Barrens"] },
		{ WHIT.."28) "..BZ["Ratchet"] },
		{ WHIT.."29) "..BZ["Honor's Stand"] },
		{ WHIT.."30) "..BZ["Northwatch Hold"] },
		{ WHIT.."31) "..BZ["Fort Triumph"] },
		{ "" },
		{ BLUE..BZ["Dustwallow Marsh"] },
		{ WHIT.."32) "..BZ["Theramore"] },
		{ WHIT.."33) "..BZ["Mudsprocket"] },
		{ "" },
		{ BLUE..BZ["Thousand Needles"] },
		{ WHIT.."34) "..BZ["Fizzle & Pozzik's Speedbarge"] },
		{ "" },
		{ BLUE..BZ["Tanaris"] },
		{ WHIT.."35) "..BZ["Gadgetzan"] },
		{ WHIT.."36) "..BZ["Bootlegger Outpost"] },
		{ WHIT.."37) "..BZ["Gunstan's Dig"] },
		{ "" },
		{ BLUE..BZ["Un'Goro Crater"] },
		{ WHIT.."38) "..BZ["Marshal's Stand"] },
		{ WHIT.."39) "..BZ["Mossy Pile"] },
		{ "" },
		{ BLUE..BZ["Silithus"] },
		{ WHIT.."40) "..BZ["Cenarion Hold"] },
		{ "" },
		{ BLUE..BZ["Felwood"] },
		{ WHIT.."41) "..BZ["Emerald Sanctuary"] },
		{ WHIT.."42) "..BZ["Wildheart Point"] },
		{ WHIT.."43) "..BZ["Whisperwind Grove"] },
		{ WHIT.."44) "..BZ["Talonbranch Glade"] },
		{ "" },
		{ BLUE..BZ["Moonglade"] },
		{ WHIT.."45) "..BZ["Moonglade"] },
		{ WHIT..INDENT.."("..L["South of the path along Lake Elune'ara"]..ALC["R-Parenthesis"] },
		{ GREN.."46) "..BZ["Nighthaven"]..ALC["L-Parenthesis"]..L["Druid Only"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Winterspring"] },
		{ WHIT.."47) "..BZ["Everlook"] },
		{ "" },
		{ BLUE..BZ["Mount Hyjal"] },
		{ WHIT.."48) "..BZ["Nordrassil"] },
		{ WHIT.."49) "..BZ["Shrine of Aviana"] },
		{ WHIT.."50) "..BZ["Shrine of Aessina"] },
		{ WHIT.."51) "..BZ["Sanctuary of Malorne"] },
		{ WHIT.."52) "..BZ["Gates of Sothann"] },
		{ "" },
		{ BLUE..BZ["Uldum"] },
		{ WHIT.."53) "..BZ["Ramkahen"] },
		{ WHIT.."54) "..BZ["Schnottz's Landing"] },
		{ WHIT.."55) "..BZ["Oasis of Vir'sar"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ CYAN.."-- : "..L["Ship / Zeppelin sailing path to destination"] },	
	},
	TransAllianceOutland = {
		ZoneName = { BZ["Outland"]..ALAN..ALC["L-Parenthesis"]..FACTION_ALLIANCE..ALC["R-Parenthesis"] },
		WorldMapID = 101,
		Faction = "Alliance",
		{ _RED..L["Portals"]..ALC["Slash"]..L["Transporter"] },
		{ PURP.." A') "..BZ["Stormwind City"]..ALC["Comma"]..BZ["Elwynn Forest"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." B') "..BZ["Sun's Reach Sanctum"]..ALC["Comma"]..BZ["Isle of Quel'Danas"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." C') "..BZ["Caverns of Time"]..ALC["Comma"]..BZ["Tanaris"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ WHIT.." 1) "..BZ["The Stair of Destiny"]..ALC["Comma"]..BZ["Hellfire Peninsula"] },
		{ WHIT.." 9) "..BZ["Shattrath City"]..ALC["Comma"]..BZ["Terokkar Forest"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Hellfire Peninsula"] },
		{ WHIT.." 1) "..BZ["The Stair of Destiny"] },
		{ WHIT.." 2) "..BZ["Shatter Point"] },
		{ WHIT.." 3) "..BZ["Honor Point"] },
		{ WHIT.." 4) "..BZ["Honor Hold"] },
		{ WHIT.." 5) "..BZ["Temple of Telhamat"] },
		{ "" },
		{ BLUE..BZ["Zangarmarsh"] },
		{ WHIT.." 6) "..BZ["Telredor"] },
		{ WHIT.." 7) "..BZ["Orebor Harborage"] },
		{ "" },
		{ BLUE..BZ["Nagrand"] },
		{ WHIT.." 8) "..BZ["Telaar"] },
		{ "" },
		{ BLUE..BZ["Terokkar Forest"] },
		{ WHIT.." 9) "..BZ["Shattrath City"] },
		{ WHIT.."10) "..BZ["Allerian Stronghold"] },
		{ GREN.."11) "..BZ["Blackwind Landing"] },
		{ GREN..INDENT..ALC["L-Parenthesis"]..L["Requires honored faction with Sha'tari Skyguard"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Shadowmoon Valley"] },
		{ WHIT.."12) "..BZ["Wildhammer Stronghold"] },
		{ GREN.."13) "..BZ["Altar of Sha'tar"]..ALC["L-Parenthesis"]..BF["The Aldor"]..ALC["R-Parenthesis"] },
		{ GREN.."14) "..BZ["Sanctum of the Stars"]..ALC["L-Parenthesis"]..BF["The Scryers"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Blade's Edge Mountains"] },
		{ WHIT.."15) "..BZ["Sylvanaar"] },
		{ WHIT.."16) "..BZ["Evergrove"] },
		{ WHIT.."17) "..BZ["Toshley's Station"] },
		{ GREN.."18) "..BZ["Skyguard Outpost"] },
		{ GREN..INDENT..ALC["L-Parenthesis"]..L["Requires honored faction with Sha'tari Skyguard"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Netherstorm"] },
		{ WHIT.."19) "..BZ["Area 52"] },
		{ WHIT.."20) "..BZ["The Stormspire"] },
		{ WHIT.."21) "..BZ["Cosmowrench"] },
		{ "" },
		{ LBLU..ACHIEVEMENTS..ALC["Colon"] },
		{ LBLU..L["Exploration"] },
		{ "Bloody Rare", "ac=1312" },
		{ "Explore Blade's Edge Mountains", "ac=865" },
		{ "Explore Hellfire Peninsula", "ac=862" },
		{ "Explore Nagrand", "ac=866" },
		{ "Explore Netherstorm", "ac=843" },
		{ "Explore Shadowmoon Valley", "ac=864" },
		{ "Explore Terokkar Forest", "ac=867" },
		{ "Explore Zangarmarsh", "ac=863" },
		{ "Medium Rare", "ac=1311" },
		{ "Outland Explorer", "ac=44" },
		{ LBLU..QUESTS_LABEL },
		{ "Blade's Edge Bomberman", "ac=1276" },
		{ "Bombs Away", "ac=1275" },
		{ "Hills Like White Elekk", "ac=939" },
		{ "Into the Nether", "ac=1194" },
		{ "Loremaster of Outland", "ac=1262" },
		{ "Mysteries of the Marsh", "ac=1190" },
		{ "Nagrand Slam", "ac=1192" },
		{ "On the Blade's Edge", "ac=1193" },
		{ "Shadow of the Betrayer", "ac=1195" },
		{ "Terror of Terokkar", "ac=1191" },
		{ "To Hellfire and Back", "ac=1189" },
	},
	TransAllianceNorthrend_WOLTKC = {
		ZoneName = { BZ["Northrend"]..ALAN..ALC["L-Parenthesis"]..FACTION_ALLIANCE..ALC["R-Parenthesis"] },
		WorldMapID = 113,
		Faction = "Alliance",
		{ _RED..BZ["Docks"] },
		{ BLUE.." A') "..BZ["Stormwind City"]..ALC["Comma"]..BZ["Elwynn Forest"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ BLUE.." B') "..BZ["Menethil Harbor"]..ALC["Comma"]..BZ["Wetlands"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ ALAN.." 1) "..BZ["Valiance Keep"]..ALC["Comma"]..BZ["Borean Tundra"] },
		{ NUTL.." 5) "..BZ["Unu'pe"]..ALC["Comma"]..BZ["Borean Tundra"] },
		{ NUTL.." 9) "..BZ["Moa'ki Harbor"]..ALC["Comma"]..BZ["Dragonblight"] },
		{ NUTL.."14) "..BZ["Kamagua"]..ALC["Comma"]..BZ["Howling Fjord"] },
		{ ALAN.."15) "..BZ["Valgarde"]..ALC["Comma"]..BZ["Howling Fjord"] },
		{ "" },
		{ _RED..L["Portals"]..ALC["Slash"]..BZ["Waygate"] },
		{ PURP.." A) "..BZ["Waygate"]..ALC["Comma"]..BZ["Sholazar Basin"] },
		{ PURP.." B) "..BZ["Wintergrasp Fortress"]..ALC["Comma"]..BZ["Wintergrasp"] },
		{ PURP.." C) "..BZ["Violet Stand"]..ALC["Comma"]..BZ["Crystalsong Forest"] },
		{ PURP.." D) "..BZ["Garm's Rise"]..ALC["Comma"]..BZ["The Storm Peaks"] },
		{ PURP.." A') "..BZ["The Shaper's Terrace"]..ALC["Comma"]..BZ["Un'Goro Crater"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ PURP.." B') "..BZ["Caverns of Time"]..ALC["Comma"]..BZ["Tanaris"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ PURP.." C') "..BZ["Stormwind City"]..ALC["Comma"]..BZ["Elwynn Forest"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ NUTL.."25) "..BZ["Dalaran"]..ALC["Comma"]..BZ["Crystalsong Forest"] },
		{ NUTL.."27) "..BZ["K3"]..ALC["Comma"]..BZ["The Storm Peaks"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Borean Tundra"] },
		{ ALAN.." 1) "..BZ["Valiance Keep"] },
		{ NUTL.." 2) "..BZ["Amber Ledge"] },
		{ "" },
		{ BLUE..BZ["Coldarra"] },
		{ NUTL.." 3) "..BZ["Transitus Shield"] },
		{ "" },
		{ BLUE..BZ["Borean Tundra"] },
		{ ALAN.." 4) "..BZ["Fizzcrank Airstrip"] },
		{ NUTL.." 5) "..BZ["Unu'pe"] },
		{ "" },
		{ BLUE..BZ["Sholazar Basin"] },
		{ NUTL.." 6) "..BZ["Nesingwary Base Camp"] },
		{ NUTL.." 7) "..BZ["River's Heart"] },
		{ "" },
		{ BLUE..BZ["Dragonblight"] },
		{ ALAN.." 8) "..BZ["Stars' Rest"] },
		{ NUTL.." 9) "..BZ["Moa'ki Harbor"] },
		{ ALAN.."10) "..BZ["Fordragon Hold"] },
		{ NUTL.."11) "..BZ["Wyrmrest Temple"] },
		{ ALAN.."12) "..BZ["Wintergarde Keep"] },
		{ "" },
		{ BLUE..BZ["Howling Fjord"] },
		{ ALAN.."13) "..BZ["Westguard Keep"] },
		{ NUTL.."14) "..BZ["Kamagua"] },
		{ ALAN.."15) "..BZ["Valgarde"] },
		{ ALAN.."16) "..BZ["Fort Wildervar"] },
		{ "" },
		{ BLUE..BZ["Grizzly Hills"] },
		{ ALAN.."17) "..BZ["Amberpine Lodge"] },
		{ ALAN.."18) "..BZ["Westfall Brigade Encampment"] },
		{ "" },
		{ BLUE..BZ["Zul'Drak"] },
		{ NUTL.."19) "..BZ["Gundrak"] },
		{ NUTL.."20) "..BZ["Zim'Torga"] },
		{ NUTL.."21) "..BZ["The Argent Stand"] },
		{ NUTL.."22) "..BZ["Light's Breach"] },
		{ NUTL.."23) "..BZ["Ebon Watch"] },
		{ "" },
		{ BLUE..BZ["Crystalsong Forest"] },
		{ ALAN.."24) "..BZ["Windrunner's Overlook"] },
		{ NUTL.."25) "..BZ["Dalaran"] },
		{ "" },
		{ BLUE..BZ["The Storm Peaks"] },
		{ ALAN.."26) "..BZ["Frosthold"] },
		{ NUTL.."27) "..BZ["K3"] },
		{ NUTL.."28) "..BZ["Bouldercrag's Refuge"] },
		{ NUTL.."29) "..BZ["Ulduar"] },
		{ NUTL.."30) "..BZ["Dun Niffelem"] },
		{ "" },
		{ BLUE..BZ["Icecrown"] },
		{ NUTL.."31) "..BZ["The Argent Vanguard"] },
		{ NUTL.."32) "..BZ["Crusaders' Pinnacle"] },
		{ NUTL.."33) "..BZ["Argent Tournament Grounds"] },
		{ NUTL.."34) "..BZ["The Shadow Vault"] },
		{ NUTL.."35) "..BZ["Death's Rise"] },
		{ "" },
		{ BLUE..BZ["Wintergrasp"] },
		{ ALAN.."36) "..BZ["Valiance Landing Camp"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ CYAN.."-- : "..L["Ship / Zeppelin sailing path to destination"] },	
		{ "" },
		{ LBLU..ACHIEVEMENTS..ALC["Colon"] },
		{ LBLU..L["Exploration"] },
		{ "Explore Borean Tundra", "ac=1264" },
		{ "Explore Crystalsong Forest", "ac=1457" },
		{ "Explore Dragonblight", "ac=1265" },
		{ "Explore Grizzly Hills", "ac=1266" },
		{ "Explore Howling Fjord", "ac=1263" },
		{ "Explore Icecrown", "ac=1270" },
		{ "Explore Sholazar Basin", "ac=1268" },
		{ "Explore Storm Peaks", "ac=1269" },
		{ "Explore Zul'Drak", "ac=1267" },
		{ "Frostbitten", "ac=2257" },
		{ "Higher Learning", "ac=1956" },
		{ "Northrend Explorer", "ac=45" },
		{ "Northern Exposure", "ac=2256" },
		{ LBLU..QUESTS_LABEL },
		{ "D.E.H.T.A's Little P.I.T.A.", "ac=561" },
		{ "Fo' Grizzle My Shizzle", "ac=37" },
		{ "Guru of Drakuru", "ac=1596" },
		{ "Honorary Frenzyheart", "ac=961" },
		{ "I've Toured the Fjord", "ac=34" },
		{ "Icecrown: The Final Goal", "ac=40" },
		{ "Into the Basin", "ac=39" },
		{ "Loremaster of Northrend", "ac=41" },
		{ "Might of Dragonblight", "ac=35" },
		{ "Mine Sweeper", "ac=1428" },
		{ "Nothing Boring About Borean", "ac=33" },
		{ "Rapid Defense", "ac=1277" },
		{ "Savior of the Oracles", "ac=962" },
		{ "The Empire of Zul'Drak", "ac=36" },
		{ "The Snows of Northrend", "ac=938" },
		{ "The Summit of Storm Peaks", "ac=38" },
		{ "Veteran of the Wrathgate", "ac=547" },
	},
	TransAlliancePandaria = {
		ZoneName = { BZ["Pandaria"]..ALAN..ALC["L-Parenthesis"]..FACTION_ALLIANCE..ALC["R-Parenthesis"] },
		WorldMapID = 424,
		Faction = "Alliance",
		{ _RED..L["Portals"] },
		{ PURP.." A) "..BZ["Paw'don Village"]..ALC["Comma"]..BZ["The Jade Forest"] },
		{ PURP.." B) "..BZ["Violet Rise"]..ALC["Comma"]..BZ["Isle of Thunder"] },
		{ PURP.." C) "..BZ["Shan'ze Dao"]..ALC["Comma"]..BZ["Townlong Steppes"] },
		{ PURP.." D) "..BZ["The Skyfire"]..ALC["Comma"]..BZ["Krasarang Wilds"] },
		{ PURP.." A') "..BZ["Stormwind City"]..ALC["Comma"]..BZ["Elwynn Forest"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ INDENT..GREY..ALC["L-Parenthesis"]..L["Gleep Chatterswitch"]..ALC["R-Parenthesis"] },
		{ PURP.." G') "..BZ["Shattrath City"]..ALC["Comma"]..BZ["Terokkar Forest"]..ALC["Comma"]..BZ["Outland"] },
		{ "" },
		{ _RED..L["Special transportation"] },
		{ ORNG.." A) "..BZ["The Arboretum"]..ALC["Comma"]..BZ["The Jade Forest"] },
		{ INDENT..GREY..L["Abandoned Kite"]..ALC["L-Parenthesis"]..L["From sea level to ground level"]..ALC["R-Parenthesis"] },
		{ ORNG.." B) "..BZ["Thunder Hold"]..ALC["Comma"]..BZ["The Jade Forest"] },
		{ INDENT..GREY..L["Abandoned Kite"]..ALC["L-Parenthesis"]..L["From sea level to ground level"]..ALC["R-Parenthesis"] },
		{ ORNG.." C) "..BZ["Strongarm Airstrip"]..ALC["Comma"]..BZ["The Jade Forest"]..ALC["Slash"]..BZ["Serenity Falls"] },
		{ INDENT..GREY..L["Abandoned Kite"]..ALC["L-Parenthesis"]..L["From sea level to ground level"]..ALC["R-Parenthesis"] },
		{ ORNG.." D) "..BZ["Winds' Edge"]..ALC["Comma"]..BZ["Valley of the Four Winds"]..ALC["Slash"]..BZ["The Deepwild"]..ALC["Comma"]..BZ["Krasarang Wilds"] },
		{ INDENT..GREY..L["Rappelling Rope"]..ALC["Slash"]..L["Climbing Rope"] },
		{ ORNG.." E) "..BZ["Whispercloud Rise"]..ALC["Slash"]..BZ["Zouchin Province"]..ALC["Comma"]..BZ["Kun-Lai Summit"] },
		{ INDENT..GREY..L["Whispercloud's Balloon"] },
		{ ORNG.." F) "..BZ["Serpent's Spine"]..ALC["Comma"]..BZ["Vale of Eternal Blossoms"]..ALC["Slash"]..BZ["Terrace of Gurthan"]..ALC["Comma"]..BZ["Dread Wastes"] },
		{ INDENT..GREY..L["Shado-Pan Rope"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["The Jade Forest"] },
		{ ALAN.." 1) "..BZ["Paw'don Village"] },
		{ ALAN.." 2) "..BZ["Pearlfin Village"] },
		{ NUTL.." 3) "..BZ["Serpent's Overlook"] },
		{ NUTL.." 4) "..BZ["Jade Temple Grounds"] },
		{ NUTL.." 5) "..BZ["Dawn's Blossom"] },
		{ NUTL.." 6) "..BZ["The Arboretum"] },
		{ NUTL.." 7) "..BZ["Tian Monastery"] },
		{ NUTL.." 8) "..BZ["Emperor's Omen"] },
		{ NUTL.." 9) "..BZ["Sri-La Village"] },
		{ "" },
		{ BLUE..BZ["Valley of the Four Winds"] },
		{ NUTL.."10) "..BZ["Pang's Stead"] },
		{ NUTL.."11) "..BZ["Grassy Cline"] },
		{ NUTL.."12) "..BZ["Halfhill"] },
		{ NUTL.."13) "..BZ["Stoneplow"] },
		{ "" },
		{ BLUE..BZ["Krasarang Wilds"] },
		{ ALAN.."14) "..BZ["Sentinel Basecamp"] },
		{ NUTL.."15) "..BZ["Cradle of Chi-Ji"] },
		{ NUTL.."16) "..BZ["Marista"] },
		{ ALAN.."17) "..BZ["The Incursion"] },
		{ NUTL.."18) "..BZ["Zhu's Watch"] },
		{ ALAN.."19) "..BZ["Lion's Landing"] },
		{ GREY..INDENT..L["Require to complete \"Meet the Scout\" quest line first."] },
		{ "" },
		{ BLUE..BZ["The Veiled Stair"] },
		{ NUTL.."20) "..BZ["Tavern in the Mists"] },
		{ "" },
		{ BLUE..BZ["Kun-Lai Summit"] },
		{ NUTL.."21) "..BZ["Binan Village"] },
		{ ALAN.."22) "..BZ["Westwind Rest"] },
		{ NUTL.."23) "..BZ["Shado-Pan Fallback"] },
		{ NUTL.."24) "..BZ["Kota Basecamp"] },
		{ NUTL.."25) "..BZ["Winter's Blossom"] },
		{ NUTL.."26) "..BZ["One Keg"] },
		{ NUTL.."27) "..BZ["Temple of the White Tiger"] },
		{ NUTL.."28) "..BZ["Zouchin Village"] },
		{ "" },
		{ BLUE..BZ["Townlong Steppes"] },
		{ NUTL.."29) "..BZ["Longying Outpost"] },
		{ NUTL.."30) "..BZ["Gao-Ran Battlefront"] },
		{ NUTL.."31) "..BZ["Rensai's Watchpost"] },
		{ NUTL.."32) "..BZ["Shado-Pan Garrison"] },
		{ "" },
		{ BLUE..BZ["Dread Wastes"] },
		{ NUTL.."33) "..BZ["The Sunset Brewgarden"] },
		{ NUTL.."34) "..BZ["Klaxxi'vess"] },
		{ ALAN.."35) "..BZ["The Lion's Redoubt"] },
		{ NUTL.."36) "..BZ["The Briny Muck"] },
		{ NUTL.."37) "..BZ["Soggy's Gamble"] },
		{ "" },
		{ BLUE..BZ["Vale of Eternal Blossoms"] },
		{ NUTL.."38) "..BZ["Serpent's Spine"] },
		{ ALAN.."39) "..BZ["Shrine of Seven Stars"] },
		{ "" },
		{ BLUE..BZ["Isle of Giants"] },
		{ ALAN.."40) "..BZ["Beeble's Wreck"] },
		{ "" },
		{ BLUE..BZ["Timeless Isle"] },
		{ ALAN.."41) "..BZ["Tushui Landing"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ "" },
		{ LBLU..ACHIEVEMENTS..ALC["Colon"] },
		{ LBLU..L["Exploration"] },
		{ "Explore Jade Forest", "ac=6351" },
		{ "Explore Krasarang Wilds", "ac=6975" },
		{ "Explore Kun-Lai Summit", "ac=6976" },
		{ "Explore Townlong Steppes", "ac=6977" },
		{ "Explore Vale of Eternal Blossoms", "ac=6979" },
		{ "Explore Valley of the Four Winds", "ac=6969" },
		{ "Pandaria Explorer", "ac=6974" },
		{ "Extreme Treasure Hunter", "ac=8726" },
		{ "Eyes On The Ground", "ac=8725" },
		{ "Finders Keepers", "ac=7282" },
		{ "Fish Tales", "ac=6846" },
		{ "Fortune of Pandaria", "ac=7995" },
		{ "Glorious!", "ac=7439" },
		{ "Gods and Monsters", "ac=8051" },
		{ "Heart of the Mantid Swarm", "ac=6857" },
		{ "Hozen in the Mist", "ac=6850" },
		{ "I'm In Your Base, Killing Your Dudes", "ac=7932" },
		{ "Is Another Man's Treasure", "ac=7284" },
		{ "Killing Time", "ac=8712" },
		{ "Legend of the Brewfathers", "ac=7230" },
		{ "Legend of the Past", "ac=8723" },
		{ "Lost and Found", "ac=7281" },
		{ "One Man's Trash...", "ac=7283" },
		{ "Pilgrimage", "ac=8724" },
		{ "Restore Balance", "ac=7381" },
		{ "Riches of Pandaria", "ac=7997" },
		{ "Rolo's Riddle", "ac=8730" },
		{ "Rumbles of Thunder", "ac=8050" },
		{ "The Dark Heart of the Mogu", "ac=6754" },
		{ "The Seven Burdens of Shaohao", "ac=6855" },
		{ "The Song of the Yaungol", "ac=6847" },
		{ "The Zandalari Prophecy", "ac=8049" },
		{ "Timeless Champion", "ac=8714" },
		{ "Timeless Legends", "ac=8784" },
		{ "Timeless Nutriment", "ac=8722" },
		{ "Treasure of Pandaria", "ac=7994" },
		{ "Treasure, Treasure Everywhere", "ac=8729" },
		{ "Wanderers, Dreamers, and You", "ac=7518" },
		{ "What Is Worth Fighting For", "ac=6858" },
		{ "Where There's Pirates, There's Booty", "ac=8727" },
		{ "Zarhym Altogether", "ac=8743" },
		{ "Zul'Again", "ac=8078" },
		{ LBLU..QUESTS_LABEL },
		{ "A Taste of History", "ac=7318" },
		{ "A Taste of Things to Come", "ac=7294" },
		{ "Ain't Lost No More", "ac=7296" },
		{ "Amber is the Color of My Energy", "ac=7312" },
		{ "Blue Response", "ac=8112" },
		{ "Boop", "ac=8118" },
		{ "Champion of Chi-Ji", "ac=7287" },
		{ "Collateral Damage", "ac=7323" },
		{ "Defender of Gods", "ac=7310" },
		{ "Direhorn in a China Shop", "ac=8120" },
		{ "Dog Pile", "ac=7320" },
		{ "Dread Haste Makes Dread Waste", "ac=6540" },
		{ "Every Day I'm Pand-a-ren", "ac=7285" },
		{ "Finish Them!", "ac=7286" },
		{ "Fire in the Yaung-hole!", "ac=7309" },
		{ "For the Ward!", "ac=8117" },
		{ "Getting Around with the Shado-Pan", "ac=7298" },
		{ "Green Acres", "ac=7292" },
		{ "How To Strain Your Dragon", "ac=7290" },
		{ "In a Trail of Smoke", "ac=7291" },
		{ "Isle of Thunder", "ac=8099" },
		{ "It Was Worth Every Ritual Stone", "ac=8101" },
		{ "Know Your Role", "ac=7308" },
		{ "Listen to the Drunk Fish", "ac=7295" },
		{ "Loner and a Rebel", "ac=7299" },
		{ "Loremaster of Pandaria", "ac=6541" },
		{ "Mighty Roamin' Krasaranger", "ac=6535" },
		{ "One Many Army", "ac=7317" },
		{ "One Step at a Time", "ac=7324" },
		{ "One Steppe Forward, Two Steppes Back", "ac=6539" },
		{ "Operation: Shieldwall Campaign", "ac=7928" },
		{ "Our Powers Combined", "ac=8119" },
		{ "Over Their Heads", "ac=7316" },
		{ "Pay to Slay", "ac=8100" },
		{ "Platform Hero", "ac=8114" },
		{ "Proven Strength", "ac=7297" },
		{ "Rally the Valley", "ac=6301" },
		{ "Ready for RAAAAIIIIDDD?!?ing", "ac=8107" },
		{ "Ready for Raiding III", "ac=7319" },
		{ "Roll Club", "ac=7322" },
		{ "Savior of Stoneplow", "ac=7502" },
		{ "Shadow Hopper", "ac=7289" },
		{ "Silent Assassin", "ac=7307" },
		{ "Slum It in the Summit", "ac=6537" },
		{ "Speed Metal", "ac=8115" },
		{ "Spreading the Warmth", "ac=7321" },
		{ "Stay Klaxxi", "ac=7313" },
		{ "Stormbreaker", "ac=8121" },
		{ "Test Drive", "ac=7314" },
		{ "The Crumble Bundle", "ac=8105" },
		{ "The Mogu Below-gu", "ac=8109" },
		{ "These Mogu Have Gotta Go-gu", "ac=8110" },
		{ "This Isn't Even My Final Form", "ac=8111" },
		{ "Thunder Plunder", "ac=8104" },
		{ "Till the Break of Dawn", "ac=7293" },
		{ "Upjade Complete", "ac=6300" },
		{ "When in Ihgaluk, Do as the Skumblade Do", "ac=8108" },
		{ "Yak Attack", "ac=7288" },
		{ "You Made Me Bleed My Own Blood", "ac=8116" },
		{ "Zandalari Library Card", "ac=8212" },
	},
}
alliance.coords = {
	TransAllianceCosmos_WOLTKC = {
		{ 1, 10001, 72, 176 },
		{ 2, 10002, 95, 193 },
		{ 3, 10003, 102, 223 },
		{ 4, 10004, 18, 226 },
		{ 5, 10005, 146, 202 },
		{ 6, 10006, 163, 334 },
		{ 7, 10007, 177, 376 },
		{ 8, 10008, 401, 304 },
		{ 9, 10009, 395, 322 },
		{10, 10010, 374, 369 },
		{11, 10011, 380, 451 },
		{12, 10012, 434, 412 },
		{13, 10013, 454, 107 },
		{14, 10014, 294, 62 },
		{15, 10015, 256, 82 },
	},
}
horde.maps = {
	TransHordeCosmos_WOLTKC = {
		ZoneName = { WORLD..HRDE..ALC["L-Parenthesis"]..FACTION_HORDE..ALC["R-Parenthesis"] },
		{ BLUE..BZ["Kalimdor"] },
		{ WHIT.." 1) "..BZ["Orgrimmar"]..ALC["Comma"].._RED..BZ["Durotar"], 10001 },
		{ WHIT.." 2) "..BZ["Thunder Bluff"]..ALC["Comma"].._RED..BZ["Mulgore"], 10002 },
		{ NUTL.." 3) "..BZ["Ratchet"]..ALC["Comma"].._RED..BZ["The Barrens"], 10003 },
		{ WHIT.." 4) "..BZ["Shrine of Remulos"]..ALC["Comma"].._RED..BZ["Moonglade"], 10004 },
		{ PURP.." B) "..BZ["The Shaper's Terrace"]..ALC["Comma"].._RED..BZ["Un'Goro Crater"] },
		{ PURP.." C) "..BZ["Caverns of Time"]..ALC["Comma"].._RED..BZ["Tanaris"] },
		{ "" },
		{ BLUE..BZ["Eastern Kingdoms"] },
		{ WHIT.." 5) "..BZ["Undercity"]..ALC["Comma"].._RED..BZ["Tirisfal Glades"], 10005 },
		{ WHIT.." 6) "..BZ["Grom'gol"]..ALC["Comma"].._RED..BZ["Stranglethorn Vale"], 10006 },
		{ NUTL.." 7) "..BZ["Booty Bay"]..ALC["Comma"].._RED..BZ["Stranglethorn Vale"], 10007 },
		{ WHIT.." 8) "..BZ["Shattered Beachhead"]..ALC["Comma"].._RED..BZ["Blasted Lands"], 10008 },
		{ WHIT.." 9) "..BZ["Silvermoon City"]..ALC["Comma"].._RED..BZ["Eversong Woods"], 10009 },
		{ WHIT.."10) "..BZ["Shattered Sun Staging Area"]..ALC["Comma"].._RED..BZ["Isle of Quel'Danas"], 10010 },
		{ "" },
		{ BLUE..BZ["Outland"] },
		{ WHIT.."11) "..BZ["The Stair of Destiny"]..ALC["Comma"].._RED..BZ["Hellfire Peninsula"], 10011 },
		{ NUTL.."12) "..BZ["Shattrath City"]..ALC["Comma"].._RED..BZ["Terokkar Forest"], 10012 },
		{ "" },
		{ BLUE..BZ["Northrend"] },
		{ WHIT.."13) "..BZ["Warsong Hold"]..ALC["Comma"].._RED..BZ["Borean Tundra"] },
		{ NUTL.."14) "..BZ["Dalaran"]..ALC["Comma"].._RED..BZ["Crystalsong Forest"] };
		{ WHIT.."15) "..BZ["Vengeance Landing"]..ALC["Comma"].._RED..BZ["Howling Fjord"] },
		{ PURP.." A) "..BZ["Waygate"]..ALC["Comma"].._RED..BZ["Sholazar Basin"] },
	},
	TransHordeEast_ClassicProgression = {
		ZoneName = { BZ["Eastern Kingdoms"]..HRDE..ALC["L-Parenthesis"]..FACTION_HORDE..ALC["R-Parenthesis"] },
		WorldMapID = 13,
		Faction = "Horde",
		{ _RED..L["Zeppelin Towers"]..ALC["Slash"]..BZ["Docks"] },
		{ ORNG.." A') "..BZ["Vengeance Landing"]..ALC["Comma"]..BZ["Howling Fjord"]..ALC["Comma"]..BZ["Northrend"] },
		{ ORNG.." B') "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ ORNG.." C') "..BZ["Ratchet"]..ALC["Comma"]..BZ["Northern Barrens"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ WHIT.."19) "..BZ["Brill"]..ALC["Comma"]..BZ["Tirisfal Glades"] },
		{ WHIT.."54) "..BZ["Grom'gol Base Camp"]..ALC["Comma"]..BZ["Northern Stranglethorn"] },
		{ WHIT.."56) "..BZ["Booty Bay"]..ALC["Comma"]..BZ["The Cape of Stranglethorn"] },
		{ "" },
		{ _RED..L["Portals"]..ALC["Slash"]..L["Orb of Translocation"] },
		{ PURP.." A) "..BZ["Hellscream's Grasp"]..ALC["Comma"]..BZ["Tol Barad Peninsula"] },
		{ PURP.." B) "..BZ["Baradin Hold"]..ALC["Comma"]..BZ["Tol Barad"] },
		{ PURP..INDENT.."("..L["Only available after winning the PvP battle"]..ALC["R-Parenthesis"] },
		{ PURP.." C) "..BZ["Dragonmaw Port"]..ALC["Comma"]..BZ["Twilight Highlands"] },
		{ PURP.." D) "..BZ["Fuselight-by-the-Sea"]..ALC["Comma"]..BZ["Badlands"] },
		{ PURP..INDENT.."("..L["Transporters by the sea and on the cliff"]..ALC["R-Parenthesis"] },
		{ PURP.." E) "..BZ["The Dark Portal"]..ALC["Comma"]..BZ["Blasted Lands"] },
		{ PURP.." A') "..BZ["The Stair of Destiny"]..ALC["Comma"]..BZ["Hellfire Peninsula"]..ALC["Comma"]..BZ["Outland"] },
		{ PURP.." B') "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ WHIT.." 3) "..BZ["Sunfury Spire"]..ALC["Comma"]..BZ["Silvermoon City"]..ALC["Comma"]..BZ["Eversong Woods"] },
		{ WHIT.."20) "..BZ["Magic Quarter"]..ALC["Comma"]..BZ["Undercity"]..ALC["Comma"]..BZ["Tirisfal Glades"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Isle of Quel'Danas"] },
		{ WHIT.." 1) "..BZ["Shattered Sun Staging Area"] },
		{ "" },
		{ BLUE..BZ["Eversong Woods"] },
		{ WHIT.." 2) "..BZ["Falconwing Square"] },
		{ WHIT.." 3) "..BZ["Silvermoon City"] },
		{ WHIT.." 4) "..BZ["Fairbreeze Village"] },
		{ "" },
		{ BLUE..BZ["Ghostlands"] },
		{ WHIT.." 5) "..BZ["Tranquillien"] },
		{ WHIT.." 6) "..BZ["Zul'Aman"] },
		{ "" },
		{ BLUE..BZ["Eastern Plaguelands"] },
		{ GREN.." 7) "..BZ["Acherus: The Ebon Hold"]..ALC["L-Parenthesis"]..L["Death Knight Only"]..ALC["R-Parenthesis"] },
		{ WHIT.." 8) "..BZ["Light's Hope Chapel"] },
		{ WHIT.." 9) "..BZ["Northpass Tower"] },
		{ WHIT.."10) "..BZ["Plaguewood Tower"] },
		{ WHIT.."11) "..BZ["Eastwall Tower"] },
		{ WHIT.."12) "..BZ["Light's Shield Tower"] },
		{ WHIT.."13) "..BZ["Crown Guard Tower"] },
		{ WHIT.."14) "..BZ["Thondroril River"] },
		{ "" },
		{ BLUE..BZ["Western Plaguelands"] },
		{ WHIT.."15) "..BZ["The Menders' Stead"] },
		{ WHIT.."16) "..BZ["Hearthglen"] },
		{ WHIT.."17) "..BZ["Andorhal"] },
		{ "" },
		{ BLUE..BZ["Tirisfal Glades"] },
		{ WHIT.."18) "..BZ["The Bulwark"] },
		{ WHIT.."19) "..BZ["Brill"] },
		{ WHIT.."20) "..BZ["Undercity"] },
		{ "" },
		{ BLUE..BZ["Silverpine Forest"] },
		{ WHIT.."21) "..BZ["Forsaken High Command"] },
		{ WHIT.."22) "..BZ["Forsaken Rear Guard"] },
		{ WHIT.."23) "..BZ["The Sepulcher"] },
		{ WHIT.."24) "..BZ["The Forsaken Front"] },
		{ "" },
		{ BLUE..BZ["Hillsbrad Foothills"] },
		{ WHIT.."25) "..BZ["Southpoint Gate"] },
		{ WHIT.."26) "..BZ["Ruins of Southshore"] },
		{ WHIT.."27) "..BZ["Eastpoint Tower"] },
		{ WHIT.."28) "..BZ["Tarren Mill"] },
		{ WHIT.."29) "..BZ["Strahnbrad"] },
		{ "" },
		{ BLUE..BZ["Arathi Highlands"] },
		{ WHIT.."30) "..BZ["Galen's Fall"] },
		{ WHIT.."31) "..BZ["Hammerfall"] },
		{ "" },
		{ BLUE..BZ["The Hinterlands"] },
		{ WHIT.."32) "..BZ["Hiri'watha Research Station"] },
		{ WHIT.."33) "..BZ["Revantusk Village"] },
		{ "" },
		{ BLUE..BZ["Twilight Highlands"] },
		{ WHIT.."34) "..BZ["Vermillion Redoubt"] },
		{ WHIT.."35) "..BZ["The Gullet"] },
		{ WHIT.."36) "..BZ["Bloodgulch"] },
		{ WHIT.."37) "..BZ["The Krazzworks"] },
		{ WHIT.."38) "..BZ["Dragonmaw Port"] },
		{ WHIT.."39) "..BZ["Crushblow"] },
		{ "" },
		{ BLUE..BZ["Badlands"] },
		{ WHIT.."40) "..BZ["Fuselight"] },
		{ WHIT.."41) "..BZ["Bloodwatcher Point"] },
		{ WHIT.."42) "..BZ["New Kargath"] },
		{ "" },
		{ BLUE..BZ["Searing Gorge"] },
		{ WHIT.."43) "..BZ["Thorium Point"] },
		{ WHIT.."44) "..BZ["Iron Summit"] },
		{ "" },
		{ BLUE..BZ["Burning Steppes"] },
		{ WHIT.."45) "..BZ["Flame Crest"] },
		{ WHIT.."46) "..BZ["Chiselgrip"] },
		{ WHIT.."47) "..BZ["Flamestar Post"] },
		{ PURP.."48) "..BZ["Terror Wing Path"].."("..L["The Bogpaddle Bullet"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Swamp of Sorrows"] },
		{ WHIT.."49) "..BZ["Bogpaddle"] },
		{ WHIT.."50) "..BZ["Stonard"] },
		{ "" },
		{ BLUE..BZ["Blasted Lands"] },
		{ WHIT.."51) "..BZ["Dreadmaul Hold"] },
		{ WHIT.."52) "..BZ["Sunveil Excursion"] },
		{ "" },
		{ BLUE..BZ["Northern Stranglethorn"] },
		{ WHIT.."53) "..BZ["Bambala"] },
		{ WHIT.."54) "..BZ["Grom'gol Base Camp"] },
		{ "" },
		{ BLUE..BZ["The Cape of Stranglethorn"] },
		{ WHIT.."55) "..BZ["Hardwrench Hideaway"] },
		{ WHIT.."56) "..BZ["Booty Bay"] },
		{ "" },
		{ BLUE..BZ["Vashj'ir"] },
		{ CYAN.."57) "..BZ["Smuggler's Scar"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] },
		{ CYAN.."58) "..BZ["Sandy Beach"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["Slash"]..L["Wind Rider"]..ALC["R-Parenthesis"] },
		{ CYAN.."59) "..BZ["Silver Tide Hollow"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] },
		{ CYAN.."60) "..BZ["Legion's Rest"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] },
		{ CYAN.."61) "..BZ["Stygian Bounty"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["Slash"]..L["Wind Rider"]..ALC["R-Parenthesis"] },
		{ CYAN.."62) "..BZ["Tenebrous Cavern"]..ALC["L-Parenthesis"]..L["Seahorse"]..ALC["R-Parenthesis"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ CYAN.."-- : "..L["Ship / Zeppelin sailing path to destination"] },
		{ GREN.."-- : "..L["Special transportation"] },
	},
	TransHordeWest_ClassicProgression = {
		ZoneName = { BZ["Kalimdor"]..HRDE..ALC["L-Parenthesis"]..FACTION_HORDE..ALC["R-Parenthesis"] },
		WorldMapID = 12,
		Faction = "Horde",
		{ _RED..L["Zeppelin Towers"]..ALC["Slash"]..BZ["Docks"] },
		{ ORNG.." A') "..BZ["Warsong Hold"]..ALC["Comma"]..BZ["Borean Tundra"]..ALC["Comma"]..BZ["Northrend"] },
		{ ORNG.." B') "..BZ["Undercity"]..ALC["Comma"]..BZ["Tirisfal Glades"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ ORNG.." C') "..BZ["Grom'gol Base Camp"]..ALC["Comma"]..BZ["Northern Stranglethorn"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ ORNG.." D') "..BZ["Booty Bay"]..ALC["Comma"]..BZ["The Cape of Stranglethorn"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ WHIT.." 2) "..BZ["Thunder Bluff"]..ALC["Comma"]..BZ["Mulgore"] },
		{ WHIT.." 5) "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"] },
		{ WHIT.."12) "..BZ["Ratchet"]..ALC["Comma"]..BZ["Northern Barrens"] },
		{ "" },
		{ _RED..L["Portals"]..ALC["Slash"]..BZ["Waygate"] },
		{ PURP.." A) "..BZ["Shaper's Terrace"]..ALC["Comma"]..BZ["Un'Goro Crater"] },
		{ PURP.." B) "..BZ["Nordune Ridge"]..ALC["Comma"]..BZ["Mount Hyjal"] },
		{ PURP.." A') "..BZ["Waygate"]..ALC["Comma"]..BZ["Sholazar Basin"]..ALC["Comma"]..BZ["Northrend"] },
		{ PURP.." B') "..BZ["Molten Front"] },
		{ PURP.." C') "..BZ["Temple of Earth"]..ALC["Comma"]..BZ["Deepholm"] },
		{ PURP.." D') "..BZ["Hellscream's Grasp"]..ALC["Comma"]..BZ["Tol Barad Peninsula"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." E') "..BZ["Vashj'ir"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." F') "..BZ["Dragonmaw Port"]..ALC["Comma"]..BZ["Twilight Highlands"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." G') "..BZ["The Dark Portal"]..ALC["Comma"]..BZ["Blasted Lands"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." H') "..BZ["Darkmoon Island"] },
		{ PURP.." I') "..BZ["Honeydew Village"]..ALC["Comma"]..BZ["The Jade Forest"]..ALC["Comma"]..BZ["Pandaria"] },
		{ WHIT.." 2) "..BZ["Spirit Rise"]..ALC["Comma"]..BZ["Thunder Bluff"]..ALC["Comma"]..BZ["Mulgore"] },
		{ WHIT.." 5) "..BZ["Valley of Spirits"]..ALC["Comma"]..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Mulgore"] },
		{ WHIT.." 1) "..BZ["Bloodhoof Village"] },
		{ WHIT.." 2) "..BZ["Thunder Bluff"] },
		{ "" },
		{ BLUE..BZ["Durotar"] },
		{ WHIT.." 3) "..BZ["Sen'jin Village"] },
		{ WHIT.." 4) "..BZ["Razor Hill"] },
		{ WHIT.." 5) "..BZ["Orgrimmar"] },
		{ "" },
		{ BLUE..BZ["Azshara"] },
		{ WHIT.." 6) "..BZ["Valormok"] },
		{ WHIT.." 7) "..BZ["Southern Rocketway"] },
		{ WHIT.." 8) "..BZ["Bilgewater Harbor"] },
		{ WHIT.." 9) "..BZ["Northern Rocketway"] },
		{ "" },
		{ BLUE..BZ["Northern Barrens"] },
		{ WHIT.."10) "..BZ["Nozzlepot's Outpost"] },
		{ WHIT.."11) "..BZ["Crossroads"] },
		{ WHIT.."12) "..BZ["Ratchet"] },
		{ "" },
		{ BLUE..BZ["Ashenvale"] },
		{ WHIT.."13) "..BZ["The Mor'Shan Ramparts"] },
		{ WHIT.."14) "..BZ["Splintertree Post"] },
		{ WHIT.."15) "..BZ["Silverwind Refuge"] },
		{ WHIT.."16) "..BZ["Hellscream's Watch"] },
		{ WHIT.."17) "..BZ["Zoram'gar Outpost"] },
		{ "" },
		{ BLUE..BZ["Stonetalon Mountains"] },
		{ WHIT.."18) "..BZ["Cliffwalker Post"] },
		{ WHIT.."19) "..BZ["The Sludgewerks"] },
		{ WHIT.."20) "..BZ["Sun Rock Retreat"] },
		{ WHIT.."21) "..BZ["Krom'gar Fortress"] },
		{ WHIT.."22) "..BZ["Malaka'jin"] },
		{ "" },
		{ BLUE..BZ["Desolace"] },
		{ WHIT.."23) "..BZ["Thunk's Abode"] },
		{ WHIT.."24) "..BZ["Karnum's Glade"] },
		{ WHIT.."25) "..BZ["Furien's Post"] },
		{ WHIT.."26) "..BZ["Ethel Rethor"] },
		{ WHIT.."27) "..BZ["Shadowprey Village"] },
		{ "" },
		{ BLUE..BZ["Southern Barrens"] },
		{ WHIT.."28) "..BZ["Hunter's Hill"] },
		{ WHIT.."29) "..BZ["Vendetta Point"] },
		{ WHIT.."30) "..BZ["Desolation Hold"] },
		{ "" },
		{ BLUE..BZ["Dustwallow Marsh"] },
		{ WHIT.."31) "..BZ["Brackenwall Village"] },
		{ WHIT.."32) "..BZ["Mudsprocket"] },
		{ "" },
		{ BLUE..BZ["Feralas"] },
		{ WHIT.."33) "..BZ["Camp Ataya"] },
		{ WHIT.."34) "..BZ["Stonemaul Hold"] },
		{ WHIT.."35) "..BZ["Camp Mojache"] },
		{ "" },
		{ BLUE..BZ["Thousand Needles"] },
		{ WHIT.."36) "..BZ["Westreach Summit"] },
		{ WHIT.."37) "..BZ["Fizzle & Pozzik's Speedbarge"] },
		{ "" },
		{ BLUE..BZ["Tanaris"] },
		{ WHIT.."38) "..BZ["Gadgetzan"] },
		{ WHIT.."39) "..BZ["Bootlegger Outpost"] },
		{ WHIT.."40) "..BZ["Dawnrise Expedition"] },
		{ "" },
		{ BLUE..BZ["Un'Goro Crater"] },
		{ WHIT.."41) "..BZ["Marshal's Stand"] },
		{ WHIT.."42) "..BZ["Mossy Pile"] },
		{ "" },
		{ BLUE..BZ["Silithus"] },
		{ WHIT.."43) "..BZ["Cenarion Hold"] },
		{ "" },
		{ BLUE..BZ["Felwood"] },
		{ WHIT.."44) "..BZ["Emerald Sanctuary"] },
		{ WHIT.."45) "..BZ["Wildheart Point"] },
		{ WHIT.."46) "..BZ["Whisperwind Grove"] },
		{ WHIT.."47) "..BZ["Irontree Clearing"] },
		{ "" },
		{ BLUE..BZ["Moonglade"] },
		{ WHIT.."48) "..BZ["Moonglade"] },
		{ WHIT..INDENT.."("..L["West of the path to Timbermaw Hold"]..ALC["R-Parenthesis"] },
		{ GREN.."49) "..BZ["Nighthaven"]..ALC["L-Parenthesis"]..L["Druid Only"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Winterspring"] },
		{ WHIT.."50) "..BZ["Everlook"] },
		{ "" },
		{ BLUE..BZ["Mount Hyjal"] },
		{ WHIT.."51) "..BZ["Nordrassil"] },
		{ WHIT.."52) "..BZ["Shrine of Aviana"] },
		{ WHIT.."53) "..BZ["Shrine of Aessina"] },
		{ WHIT.."54) "..BZ["Sanctuary of Malorne"] },
		{ WHIT.."55) "..BZ["Gates of Sothann"] },
		{ "" },
		{ BLUE..BZ["Uldum"] },
		{ WHIT.."56) "..BZ["Ramkahen"] },
		{ WHIT.."57) "..BZ["Schnottz's Landing"] },
		{ WHIT.."58) "..BZ["Oasis of Vir'sar"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ CYAN.."-- : "..L["Ship / Zeppelin sailing path to destination"] },	
	},
	TransHordeOutland = {
		ZoneName = { BZ["Outland"]..HRDE..ALC["L-Parenthesis"]..FACTION_HORDE..ALC["R-Parenthesis"] },
		WorldMapID = 101,
		Faction = "Horde",
		{ _RED..L["Portals"]..ALC["Slash"]..L["Transporter"] },
		{ PURP.." A') "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ PURP.." B') "..BZ["Sun's Reach Sanctum"]..ALC["Comma"]..BZ["Isle of Quel'Danas"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ PURP.." C') "..BZ["Caverns of Time"]..ALC["Comma"]..BZ["Tanaris"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ WHIT.." 1) "..BZ["The Stair of Destiny"]..ALC["Comma"]..BZ["Hellfire Peninsula"] },
		{ WHIT.." 8) "..BZ["Shattrath City"]..ALC["Comma"]..BZ["Terokkar Forest"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Hellfire Peninsula"] },
		{ WHIT.." 1) "..BZ["The Stair of Destiny"] },
		{ WHIT.." 2) "..BZ["Thrallmar"] },
		{ WHIT.." 3) "..BZ["Spinebreaker Post"] },
		{ WHIT.." 4) "..BZ["Falcon Watch"] },
		{ "" },
		{ BLUE..BZ["Zangarmarsh"] },
		{ WHIT.." 5) "..BZ["Swamprat Post"] },
		{ WHIT.." 6) "..BZ["Zabra'jin"] },
		{ "" },
		{ BLUE..BZ["Nagrand"] },
		{ WHIT.." 7) "..BZ["Garadar"] },
		{ "" },
		{ BLUE..BZ["Terokkar Forest"] },
		{ WHIT.." 8) "..BZ["Shattrath City"] },
		{ WHIT.." 9) "..BZ["Stonebreaker Hold"] },
		{ GREN.."10) "..BZ["Blackwind Landing"] },
		{ GREN..INDENT..ALC["L-Parenthesis"]..L["Requires honored faction with Sha'tari Skyguard"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Shadowmoon Valley"] },
		{ WHIT.."11) "..BZ["Shadowmoon Village"] },
		{ GREN.."12) "..BZ["Altar of Sha'tar"]..ALC["L-Parenthesis"]..BF["The Aldor"]..ALC["R-Parenthesis"] },
		{ GREN.."13) "..BZ["Sanctum of the Stars"]..ALC["L-Parenthesis"]..BF["The Scryers"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Blade's Edge Mountains"] },
		{ WHIT.."14) "..BZ["Thunderlord Stronghold"] },
		{ WHIT.."15) "..BZ["Evergrove"] },
		{ WHIT.."16) "..BZ["Mok'Nathal Village"] },
		{ GREN.."17) "..BZ["Skyguard Outpost"] },
		{ GREN..INDENT..ALC["L-Parenthesis"]..L["Requires honored faction with Sha'tari Skyguard"]..ALC["R-Parenthesis"] },
		{ "" },
		{ BLUE..BZ["Netherstorm"] },
		{ WHIT.."18) "..BZ["Area 52"] },
		{ WHIT.."19) "..BZ["The Stormspire"] },
		{ WHIT.."20) "..BZ["Cosmowrench"] },
		{ "" },
		{ LBLU..ACHIEVEMENTS..ALC["Colon"] },
		{ LBLU..L["Exploration"] },
		{ "Bloody Rare", "ac=1312" },
		{ "Explore Blade's Edge Mountains", "ac=865" },
		{ "Explore Hellfire Peninsula", "ac=862" },
		{ "Explore Nagrand", "ac=866" },
		{ "Explore Netherstorm", "ac=843" },
		{ "Explore Shadowmoon Valley", "ac=864" },
		{ "Explore Terokkar Forest", "ac=867" },
		{ "Explore Zangarmarsh", "ac=863" },
		{ "Medium Rare", "ac=1311" },
		{ "Outland Explorer", "ac=44" },
		{ LBLU..QUESTS_LABEL },
		{ "Blade's Edge Bomberman", "ac=1276" },
		{ "Bombs Away", "ac=1275" },
		{ "Hills Like White Elekk", "ac=939" },
		{ "Into the Nether", "ac=1194" },
		{ "Loremaster of Outland", "ac=1262" },
		{ "Mysteries of the Marsh", "ac=1190" },
		{ "Nagrand Slam", "ac=1273" },
		{ "On the Blade's Edge", "ac=1193" },
		{ "Shadow of the Betrayer", "ac=1195" },
		{ "Terror of Terokkar", "ac=1272" },
		{ "To Hellfire and Back", "ac=1271" },
	},
	TransHordeNorthrend_WOLTKC = {
		ZoneName = { BZ["Northrend"]..HRDE..ALC["L-Parenthesis"]..FACTION_HORDE..ALC["R-Parenthesis"] },
		WorldMapID = 113,
		Faction = "Horde",
		{ _RED..L["Zeppelin Towers"] },
		{ BLUE.." A') "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ BLUE.." B') "..BZ["Undercity"]..ALC["Comma"]..BZ["Tirisfal Glades"]..ALC["Comma"]..BZ["Eastern Kingdoms"] },
		{ HRDE.." 1) "..BZ["Warsong Hold"]..ALC["Comma"]..BZ["Borean Tundra"] },
		{ HRDE.."16) "..BZ["Vengeance Landing"]..ALC["Comma"]..BZ["Howling Fjord"] },
		{ "" },
		{ _RED..BZ["Docks"] },
		{ NUTL.." 6) "..BZ["Unu'pe"]..ALC["Comma"]..BZ["Borean Tundra"] },
		{ NUTL.."10) "..BZ["Moa'ki Harbor"]..ALC["Comma"]..BZ["Dragonblight"] },
		{ NUTL.."14) "..BZ["Kamagua"]..ALC["Comma"]..BZ["Howling Fjord"] },
		{ "" },
		{ _RED..L["Portals"]..ALC["Slash"]..BZ["Waygate"] },
		{ PURP.." A) "..BZ["Waygate"]..ALC["Comma"]..BZ["Sholazar Basin"] },
		{ PURP.." B) "..BZ["Wintergrasp Fortress"]..ALC["Comma"]..BZ["Wintergrasp"] },
		{ PURP.." C) "..BZ["Violet Stand"]..ALC["Comma"]..BZ["Crystalsong Forest"] },
		{ PURP.." D) "..BZ["Garm's Rise"]..ALC["Comma"]..BZ["The Storm Peaks"] },
		{ PURP.." A') "..BZ["The Shaper's Terrace"]..ALC["Comma"]..BZ["Un'Goro Crater"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ PURP.." B') "..BZ["Caverns of Time"]..ALC["Comma"]..BZ["Tanaris"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ PURP.." C') "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ NUTL.."27) "..BZ["Dalaran"]..ALC["Comma"]..BZ["Crystalsong Forest"] },
		{ NUTL.."28) "..BZ["K3"]..ALC["Comma"]..BZ["The Storm Peaks"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["Borean Tundra"] },
		{ HRDE.." 1) "..BZ["Warsong Hold"] },
		{ NUTL.." 2) "..BZ["Amber Ledge"] },
		{ "" },
		{ BLUE..BZ["Coldarra"] },
		{ NUTL.." 3) "..BZ["Transitus Shield"] },
		{ "" },
		{ BLUE..BZ["Borean Tundra"] },
		{ HRDE.." 4) "..BZ["Bor'gorok Outpost"] },
		{ HRDE.." 5) "..BZ["Taunka'le Village"] },
		{ NUTL.." 6) "..BZ["Unu'pe"] },
		{ "" },
		{ BLUE..BZ["Sholazar Basin"] },
		{ NUTL.." 7) "..BZ["Nesingwary Base Camp"] },
		{ NUTL.." 8) "..BZ["River's Heart"] },
		{ "" },
		{ BLUE..BZ["Dragonblight"] },
		{ HRDE.." 9) "..BZ["Agmar's Hammer"] },
		{ NUTL.."10) "..BZ["Moa'ki Harbor"] },
		{ HRDE.."11) "..BZ["Kor'kron Vanguard"] },
		{ NUTL.."12) "..BZ["Wyrmrest Temple"] },
		{ HRDE.."13) "..BZ["Venomspite"] },
		{ "" },
		{ BLUE..BZ["Howling Fjord"] },
		{ NUTL.."14) "..BZ["Kamagua"] },
		{ HRDE.."15) "..BZ["New Agamand"] },
		{ HRDE.."16) "..BZ["Vengeance Landing"] },
		{ HRDE.."17) "..BZ["Apothecary Camp"] },
		{ HRDE.."18) "..BZ["Camp Winterhoof"] },
		{ "" },
		{ BLUE..BZ["Grizzly Hills"] },
		{ HRDE.."19) "..BZ["Conquest Hold"] },
		{ HRDE.."20) "..BZ["Camp Oneqwah"] },
		{ "" },
		{ BLUE..BZ["Zul'Drak"] },
		{ NUTL.."21) "..BZ["Gundrak"] },
		{ NUTL.."22) "..BZ["Zim'Torga"] },
		{ NUTL.."23) "..BZ["The Argent Stand"] },
		{ NUTL.."24) "..BZ["Light's Breach"] },
		{ NUTL.."25) "..BZ["Ebon Watch"] },
		{ "" },
		{ BLUE..BZ["Crystalsong Forest"] },
		{ HRDE.."26) "..BZ["Sunreaver's Command"] },
		{ NUTL.."27) "..BZ["Dalaran"] },
		{ "" },
		{ BLUE..BZ["The Storm Peaks"] },
		{ NUTL.."28) "..BZ["K3"] },
		{ HRDE.."29) "..BZ["Camp Tunka'lo"] },
		{ HRDE.."30) "..BZ["Grom'arsh Crash-Site"] },
		{ NUTL.."31) "..BZ["Bouldercrag's Refuge"] },
		{ NUTL.."32) "..BZ["Ulduar"] },
		{ NUTL.."33) "..BZ["Dun Niffelem"] },
		{ "" },
		{ BLUE..BZ["Icecrown"] },
		{ NUTL.."34) "..BZ["The Argent Vanguard"] },
		{ NUTL.."35) "..BZ["Crusaders' Pinnacle"] },
		{ NUTL.."36) "..BZ["Argent Tournament Grounds"] },
		{ NUTL.."37) "..BZ["The Shadow Vault"] },
		{ NUTL.."38) "..BZ["Death's Rise"] },
		{ "" },
		{ BLUE..BZ["Wintergrasp"] },
		{ HRDE.."39) "..BZ["Warsong Camp"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ CYAN.."-- : "..L["Ship / Zeppelin sailing path to destination"] },	
		{ "" },
		{ LBLU..ACHIEVEMENTS..ALC["Colon"] },
		{ LBLU..L["Exploration"] },
		{ "Explore Borean Tundra", "ac=1264" },
		{ "Explore Crystalsong Forest", "ac=1457" },
		{ "Explore Dragonblight", "ac=1265" },
		{ "Explore Grizzly Hills", "ac=1266" },
		{ "Explore Howling Fjord", "ac=1263" },
		{ "Explore Icecrown", "ac=1270" },
		{ "Explore Sholazar Basin", "ac=1268" },
		{ "Explore Storm Peaks", "ac=1269" },
		{ "Explore Zul'Drak", "ac=1267" },
		{ "Frostbitten", "ac=2257" },
		{ "Higher Learning", "ac=1956" },
		{ "Northrend Explorer", "ac=45" },
		{ "Northern Exposure", "ac=2256" },
		{ LBLU..QUESTS_LABEL },
		{ "D.E.H.T.A's Little P.I.T.A.", "ac=561" },
		{ "Fo' Grizzle My Shizzle", "ac=1357" },
		{ "Guru of Drakuru", "ac=1596" },
		{ "Honorary Frenzyheart", "ac=961" },
		{ "I've Toured the Fjord", "ac=1356" },
		{ "Icecrown: The Final Goal", "ac=40" },
		{ "Into the Basin", "ac=39" },
		{ "Loremaster of Northrend", "ac=41" },
		{ "Might of Dragonblight", "ac=1359" },
		{ "Mine Sweeper", "ac=1428" },
		{ "Nothing Boring About Borean", "ac=1358" },
		{ "Rapid Defense", "ac=1277" },
		{ "Savior of the Oracles", "ac=962" },
		{ "The Empire of Zul'Drak", "ac=36" },
		{ "The Snows of Northrend", "ac=938" },
		{ "The Summit of Storm Peaks", "ac=38" },
		{ "Veteran of the Wrathgate", "ac=547" },
	},
	TransHordePandaria = {
		ZoneName = { BZ["Pandaria"]..HRDE..ALC["L-Parenthesis"]..FACTION_HORDE..ALC["R-Parenthesis"] },
		WorldMapID = 424,
		Faction = "Horde",
		{ _RED..L["Portals"] },
		{ PURP.." A) "..BZ["Honeydew Village"]..ALC["Comma"]..BZ["The Jade Forest"] },
		{ PURP.." B) "..BZ["Dawnseeker Promontory"]..ALC["Comma"]..BZ["Isle of Thunder"] },
		{ PURP.." C) "..BZ["Shan'ze Dao"]..ALC["Comma"]..BZ["Townlong Steppes"] },
		{ PURP.." D) "..BZ["Sparkrocket Outpost"]..ALC["Comma"]..BZ["Krasarang Wilds"] },
		{ PURP.." E) "..BZ["Ruins of Ogudei"]..ALC["Comma"]..BZ["Krasarang Wilds"] },
		{ PURP.." A') "..BZ["Orgrimmar"]..ALC["Comma"]..BZ["Durotar"]..ALC["Comma"]..BZ["Kalimdor"] },
		{ "" },
		{ _RED..L["Special transportation"] },
		{ ORNG.." A) "..BZ["The Arboretum"]..ALC["Comma"]..BZ["The Jade Forest"] },
		{ INDENT..GREY..L["Abandoned Kite"]..ALC["L-Parenthesis"]..L["From sea level to ground level"]..ALC["R-Parenthesis"] },
		{ ORNG.." B) "..BZ["Thunder Hold"]..ALC["Comma"]..BZ["The Jade Forest"] },
		{ INDENT..GREY..L["Abandoned Kite"]..ALC["L-Parenthesis"]..L["From sea level to ground level"]..ALC["R-Parenthesis"] },
		{ ORNG.." C) "..BZ["Strongarm Airstrip"]..ALC["Comma"]..BZ["The Jade Forest"]..ALC["Slash"]..BZ["Serenity Falls"] },
		{ INDENT..GREY..L["Abandoned Kite"]..ALC["L-Parenthesis"]..L["From sea level to ground level"]..ALC["R-Parenthesis"] },
		{ ORNG.." D) "..BZ["Winds' Edge"]..ALC["Comma"]..BZ["Valley of the Four Winds"]..ALC["Slash"]..BZ["The Deepwild"]..ALC["Comma"]..BZ["Krasarang Wilds"] },
		{ INDENT..GREY..L["Rappelling Rope"]..ALC["Slash"]..L["Climbing Rope"] },
		{ ORNG.." E) "..BZ["Whispercloud Rise"]..ALC["Slash"]..BZ["Zouchin Province"]..ALC["Comma"]..BZ["Kun-Lai Summit"] },
		{ INDENT..GREY..L["Whispercloud's Balloon"] },
		{ ORNG.." F) "..BZ["Serpent's Spine"]..ALC["Comma"]..BZ["Vale of Eternal Blossoms"]..ALC["Slash"]..BZ["Terrace of Gurthan"]..ALC["Comma"]..BZ["Dread Wastes"] },
		{ INDENT..GREY..L["Shado-Pan Rope"] },
		{ "" },
		{ _RED..L["Taxi Nodes"] },
		{ BLUE..BZ["The Jade Forest"] },
		{ HRDE.." 1) "..BZ["Honeydew Village"] },
		{ NUTL.." 2) "..BZ["Tian Monastery"] },
		{ NUTL.." 3) "..BZ["Emperor's Omen"] },
		{ NUTL.." 4) "..BZ["Sri-La Village"] },
		{ NUTL.." 5) "..BZ["Dawn's Blossom"] },
		{ NUTL.." 6) "..BZ["The Arboretum"] },
		{ NUTL.." 7) "..BZ["Jade Temple Grounds"] },
		{ NUTL.." 8) "..BZ["Serpent's Overlook"] },
		{ HRDE.." 9) "..BZ["Grookin Hill"] },
		{ "" },
		{ BLUE..BZ["Valley of the Four Winds"] },
		{ NUTL.."10) "..BZ["Pang's Stead"] },
		{ NUTL.."11) "..BZ["Grassy Cline"] },
		{ NUTL.."12) "..BZ["Halfhill"] },
		{ NUTL.."13) "..BZ["Stoneplow"] },
		{ "" },
		{ BLUE..BZ["Krasarang Wilds"] },
		{ HRDE.."14) "..BZ["Dawnchaser Retreat"] },
		{ NUTL.."15) "..BZ["Cradle of Chi-Ji"] },
		{ NUTL.."16) "..BZ["Marista"] },
		{ HRDE.."17) "..BZ["Thunder Cleft"] },
		{ NUTL.."18) "..BZ["Zhu's Watch"] },
		{ HRDE.."19) "..BZ["Domination Point"] },
		{ GREY..INDENT..L["Require to complete \"Meet the Scout\" quest line first."] },
		{ "" },
		{ BLUE..BZ["The Veiled Stair"] },
		{ NUTL.."20) "..BZ["Tavern in the Mists"] },
		{ "" },
		{ BLUE..BZ["Kun-Lai Summit"] },
		{ NUTL.."21) "..BZ["Binan Village"] },
		{ HRDE.."22) "..BZ["Eastwind Rest"] },
		{ NUTL.."23) "..BZ["Shado-Pan Fallback"] },
		{ NUTL.."24) "..BZ["Kota Basecamp"] },
		{ NUTL.."25) "..BZ["Winter's Blossom"] },
		{ NUTL.."26) "..BZ["One Keg"] },
		{ NUTL.."27) "..BZ["Temple of the White Tiger"] },
		{ NUTL.."28) "..BZ["Zouchin Village"] },
		{ HRDE.."29) "..BZ["Serpent's Spine"] },
		{ "" },
		{ BLUE..BZ["Townlong Steppes"] },
		{ NUTL.."30) "..BZ["Longying Outpost"] },
		{ NUTL.."31) "..BZ["Gao-Ran Battlefront"] },
		{ NUTL.."32) "..BZ["Rensai's Watchpost"] },
		{ NUTL.."33) "..BZ["Shado-Pan Garrison"] },
		{ "" },
		{ BLUE..BZ["Dread Wastes"] },
		{ NUTL.."34) "..BZ["The Sunset Brewgarden"] },
		{ NUTL.."35) "..BZ["Klaxxi'vess"] },
		{ NUTL.."36) "..BZ["The Briny Muck"] },
		{ NUTL.."37) "..BZ["Soggy's Gamble"] },
		{ "" },
		{ BLUE..BZ["Vale of Eternal Blossoms"] },
		{ NUTL.."38) "..BZ["Serpent's Spine"] },    
		{ HRDE.."39) "..BZ["Shrine of Two Moons"] },
		{ "" },
		{ BLUE..BZ["Isle of Giants"] },
		{ HRDE.."40) "..BZ["Bozzle's Wreck"] },
		{ "" },
		{ BLUE..BZ["Timeless Isle"] },
		{ HRDE.."41) "..BZ["Huojin Landing"] },
		{ "" },
		{ _RED..L["Legend"] },
		{ PURP.."-- : "..L["Portal / Waygate Path to the destination"] },
		{ "" },
		{ LBLU..ACHIEVEMENTS..ALC["Colon"] },
		{ LBLU..L["Exploration"] },
		{ "Explore Jade Forest", "ac=6351" },
		{ "Explore Krasarang Wilds", "ac=6975" },
		{ "Explore Kun-Lai Summit", "ac=6976" },
		{ "Explore Townlong Steppes", "ac=6977" },
		{ "Explore Vale of Eternal Blossoms", "ac=6979" },
		{ "Explore Valley of the Four Winds", "ac=6969" },
		{ "Extreme Treasure Hunter", "ac=8726" },
		{ "Pandaria Explorer", "ac=6974" },
		{ "Eyes On The Ground", "ac=8725" },
		{ "Finders Keepers", "ac=7282" },
		{ "Fish Tales", "ac=6846" },
		{ "Fortune of Pandaria", "ac=7995" },
		{ "Glorious!", "ac=7439" },
		{ "Gods and Monsters", "ac=8051" },
		{ "Heart of the Mantid Swarm", "ac=6857" },
		{ "Hozen in the Mist", "ac=6850" },
		{ "I'm In Your Base, Killing Your Dudes", "ac=7932" },
		{ "Is Another Man's Treasure", "ac=7284" },
		{ "Killing Time", "ac=8712" },
		{ "Legend of the Brewfathers", "ac=7230" },
		{ "Legend of the Past", "ac=8723" },
		{ "Lost and Found", "ac=7281" },
		{ "One Man's Trash...", "ac=7283" },
		{ "Pilgrimage", "ac=8724" },
		{ "Restore Balance", "ac=7381" },
		{ "Riches of Pandaria", "ac=7997" },
		{ "Rolo's Riddle", "ac=8730" },
		{ "Rumbles of Thunder", "ac=8050" },
		{ "The Dark Heart of the Mogu", "ac=6754" },
		{ "The Seven Burdens of Shaohao", "ac=6855" },
		{ "The Song of the Yaungol", "ac=6847" },
		{ "The Zandalari Prophecy", "ac=8049" },
		{ "Timeless Champion", "ac=8714" },
		{ "Timeless Legends", "ac=8784" },
		{ "Timeless Nutriment", "ac=8722" },
		{ "Treasure of Pandaria", "ac=7994" },
		{ "Treasure, Treasure Everywhere", "ac=8729" },
		{ "Wanderers, Dreamers, and You", "ac=7518" },
		{ "What Is Worth Fighting For", "ac=6858" },
		{ "Where There's Pirates, There's Booty", "ac=8727" },
		{ "Zarhym Altogether", "ac=8743" },
		{ "Zul'Again", "ac=8078" },
		{ LBLU..QUESTS_LABEL },
		{ "A Taste of History", "ac=7318" },
		{ "A Taste of Things to Come", "ac=7294" },
		{ "Ain't Lost No More", "ac=7296" },
		{ "Amber is the Color of My Energy", "ac=7312" },
		{ "Blue Response", "ac=8112" },
		{ "Boop", "ac=8118" },
		{ "Champion of Chi-Ji", "ac=7287" },
		{ "Collateral Damage", "ac=7323" },
		{ "Defender of Gods", "ac=7310" },
		{ "Direhorn in a China Shop", "ac=8120" },
		{ "Dog Pile", "ac=7320" },
		{ "Dominance Offensive Campaign", "ac=7929" },
		{ "Dread Haste Makes Dread Waste", "ac=6540" },
		{ "Every Day I'm Pand-a-ren", "ac=7285" },
		{ "Finish Them!", "ac=7286" },
		{ "Fire in the Yaung-hole!", "ac=7309" },
		{ "For the Ward!", "ac=8117" },
		{ "Getting Around with the Shado-Pan", "ac=7298" },
		{ "Green Acres", "ac=7292" },
		{ "How To Strain Your Dragon", "ac=7290" },
		{ "In a Trail of Smoke", "ac=7291" },
		{ "Isle of Thunder", "ac=8099" },
		{ "It Was Worth Every Ritual Stone", "ac=8101" },
		{ "Know Your Role", "ac=7308" },
		{ "Listen to the Drunk Fish", "ac=7295" },
		{ "Loner and a Rebel", "ac=7299" },
		{ "Loremaster of Pandaria", "ac=6541" },
		{ "Mighty Roamin' Krasaranger", "ac=6536" },
		{ "One Many Army", "ac=7317" },
		{ "One Step at a Time", "ac=7324" },
		{ "One Steppe Forward, Two Steppes Back", "ac=6539" },
		{ "Our Powers Combined", "ac=8119" },
		{ "Over Their Heads", "ac=7316" },
		{ "Pay to Slay", "ac=8100" },
		{ "Platform Hero", "ac=8114" },
		{ "Proven Strength", "ac=7297" },
		{ "Rally the Valley", "ac=6301" },
		{ "Ready for RAAAAIIIIDDD?!?ing", "ac=8107" },
		{ "Ready for Raiding III", "ac=7319" },
		{ "Roll Club", "ac=7322" },
		{ "Savior of Stoneplow", "ac=7502" },
		{ "Shadow Hopper", "ac=7289" },
		{ "Silent Assassin", "ac=7307" },
		{ "Slum It in the Summit", "ac=6538" },
		{ "Speed Metal", "ac=8115" },
		{ "Spreading the Warmth", "ac=7321" },
		{ "Stay Klaxxi", "ac=7313" },
		{ "Stormbreaker", "ac=8121" },
		{ "Test Drive", "ac=7314" },
		{ "The Crumble Bundle", "ac=8105" },
		{ "The Mogu Below-gu", "ac=8109" },
		{ "These Mogu Have Gotta Go-gu", "ac=8110" },
		{ "This Isn't Even My Final Form", "ac=8111" },
		{ "Thunder Plunder", "ac=8104" },
		{ "Till the Break of Dawn", "ac=7293" },
		{ "Upjade Complete", "ac=6534" },
		{ "When in Ihgaluk, Do as the Skumblade Do", "ac=8108" },
		{ "Yak Attack", "ac=7288" },
		{ "You Made Me Bleed My Own Blood", "ac=8116" },
		{ "Zandalari Library Card", "ac=8212" },
	},
}
horde.coords = {
	TransHordeCosmos_WOLTKC = {
		{ 1, 10001, 173, 288 },
		{ 2, 10002, 112, 337 },
		{ 3, 10003, 163, 334 },
		{ 4, 10004, 146, 202 },
		{ 5, 10005, 389, 218 },
		{ 6, 10006, 389, 420 },
		{ 7, 10007, 382, 451 },
		{ 8, 10008, 436, 414 },
		{ 9, 10009, 456, 145 },
		{10, 10010, 456, 108 },
		{11, 10011, 294, 62 },
		{12, 10012, 256, 82 },
	}
}
data.maps = {
}
data.coords = {
}



